<a href="https://colab.research.google.com/github/wasimnawaz1/programming_4_AI/blob/main/Programming_for_AI%2C_Lectures_(Week_5-8)_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 5-8: Introduction to **AI271 Programming for AI**

### **Link to find the lecture:**
https://github.com/wasimnawaz1/programming_4_AI

# Data Preparation (Preprocessing)

Data preparation is the process of constructing a **clean dataset** from one or more sources such that the data can be fed into subsequent stages of a data science pipeline.

Common data preparation tasks include:
- Handling missing values
- Outlier detection
- Feature/variable scaling
- Feature encoding

Data preparation is often a time-consuming process. Python provides us with a specialized library, **Pandas**, for data preparation and analysis.

### Pandas for Data Preparation

**Pandas** is a specialized library that makes the tedious tasks of data preparation and analysis easy. It uses two data structures:

Pandas is a powerhouse for data manipulation and analysis, especially when dealing with structured data.

- **Series** — for one-dimensional data
- **DataFrame** — for multi-dimensional (tabular) data

These data structures are designed to work with labeled or relational data, and are suitable to manage data stored in tabular formats such as databases, Excel spreadsheets and CSV files.

Since we shall be working with Numpy and Pandas, we import both. The general practice is:

In [ ]:
import pandas as pd
import numpy as np

### Pandas Data Structures

All operations for data pre-processing and analysis are centralized on two data structures:
- **Series** — designed to store a sequence of one-dimensional data
- **DataFrame** — designed to handle data having several dimensions

#### The Series

The `Series` data structure, similar to a NumPy array, is used to handle one-dimensional data. It provides features not provided by simple NumPy arrays. To create a Series object, we use the `Series()` constructor.

In [ ]:
myseries = pd.Series([1, -3, 5.5, -20])  # note capital S in Series
myseries

### Series Structure

- `dtype: int64` means the data type of values in a Series is integer of 64 bits.
- A Series object consists of **two arrays**: index and value, associated with each other.
- Pandas assigns **numerical indices starting from 0** if we do not specify any index.

It is sometimes preferable to create a Series object using **descriptive and meaningful labels**. We can assign indices during the constructor call:

In [ ]:
myseries2 = pd.Series([1, -3, 5, 20], index=['a', 'b', 'c', 'd'])
myseries2

### Series Attributes: `.values` and `.index`

Two attributes of the Series data structure — `index` and `values` — can be used to view the values and index separately.

In [ ]:
myseries2.values

type(myseries2.values)

In [ ]:
myseries2.index

### Accessing Elements of a Series

The elements of a Series can be accessed in the same way we access array elements.

In [ ]:
print(myseries2)

# myseries2[2]

myseries2.iloc[3]

In [ ]:
display(myseries2)


myseries2[0:2]

In [ ]:
print(myseries2)

myseries2['b']

In [ ]:
print(myseries2)

myseries2[  ['a','d']  ]  # Note: double brackets for list of labels

### Modifying Series Values

We can select the value by index or label, and assign a different value to it:

In [ ]:
print(myseries2)


myseries2['c'] = 10
myseries2

### Creating a Series from a NumPy Array

In [ ]:
myarray = np.array([1,2,-5, 3,10, -4, -9, 3, 5, -100])
myseries3 = pd.Series(myarray)
myseries3

### Filtering and Math Operations on a Series

Most operations performed on simple NumPy arrays are valid on a Series data structure. We can use **conditional operators** to filter or select values.

In [ ]:
# Get values greater than 0
print(myseries3)

# myseries3 > 0


myseries3[myseries3 > -10]

# myseries3

In [ ]:
# Logarithm of values (NaN returned for negative numbers)
np.log(myseries3)

### NaN Values and Unique/Count Operations

**NaN** (Not a Number) values are used to indicate an empty field or an undefinable quantity.

To create null values in Pandas or NumPy, we can use:

-   `np.nan`: This is NumPy's representation for "Not a Number." It's commonly used for missing numerical data.
-   `None`: This is Python's built-in null object. Pandas will often treat `None` as `np.nan` in numerical Series/DataFrames, but it maintains `None` for object-type Series/DataFrames.

- The `isnull()` and `notnull()` functions of Pandas help identify indices without a value.

Let us create a Series `mycolors` to perform some common operations:

In [ ]:
import pandas as pd
import numpy as np
mycolors = pd.Series([1,2,3,4,np.nan,None,3,2,1],
    index=['white','black','blue','green','blue', 'green','yellow','black','red'])

print(mycolors)

# print(mycolors.isnull()) # returns True when the value is null

print(f'\n\n\n', mycolors.notnull())  # returns True when the value is NOT null

In [ ]:
# Get unique values
print(mycolors)
mycolors.unique()

In [ ]:
# Count how many times each value appears
mycolors.value_counts()

### The `isin()` Function

To find a particular value contained in a Series, we use `isin()` that evaluates the **membership**. It returns a Boolean value (True/False), which can be used to **filter** the data.

In [ ]:
# Search values 3 and 7 in mycolors
print(mycolors)

mycolors.isin([3,7])

In [ ]:
# Use Boolean result as index to filter the Series

print(mycolors)
mycolors[ mycolors.isin([2, 3]) ]

### Creating a Series from a Dictionary

In [ ]:
import pandas as pd
mydict = {'White': 1000.01, 'Black': 500, 'Red': 200, 'Green': 1000}
myseries = pd.Series(mydict)
myseries

### Question: Create a Pandas Series of first 100 natural numbers. Now create another Series from the first series that has only even numbers from 50 to 100.

### Announcement: Quiz 2 from notebooks 3 and 4 on coming Monday.

### The DataFrame

The **DataFrame** is a tabular data structure very similar to an Excel Spreadsheet. It can be considered an extension of a Series to multiple dimensions.

- The DataFrame consists of an ordered group of columns.
- Every column contains values of numeric, string, Boolean, etc. types.

A DataFrame can be created by passing a **dictionary object** to the `DataFrame()` constructor:

In [ ]:
# Creating DataFrames ---

import pandas as pd

# **Creating a Simple DataFrame from a Dictionary**
# DataFrames can be created from various sources, including Python dictionaries,
# lists of dictionaries, or by reading files like CSVs.
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 40],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
print("\nPandas DataFrame from dictionary:")
display(df)

In [ ]:
### saving a dataframe as a csv/Excel file.
df.to_csv('/content/my_csv.csv')   # , keyword index=False avoids saving the index.

df.to_excel('/content/my_csv.xlsx')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
### loading a csv/Excel file in a dataframe.

loaded_csv = pd.read_csv('/content/my_csv.csv')
display(loaded_csv)

print(f'\n\n\n')

loaded_excel = pd.read_excel('/content/my_csv.xlsx')
display(loaded_excel)

In [ ]:
### loading a csv/Excel file in a dataframe.

loaded_csv = pd.read_csv('/content/my_csv.csv', index_col=0)  # Use the first column (column 0) as the row index.
display(loaded_csv)

print(f'\n\n\n')

loaded_excel = pd.read_excel('/content/my_csv.xlsx', index_col=0)
display(loaded_excel)

In [ ]:
# Example: Creating a DataFrame from a list of lists
data_list = [['David', 40, 'Houston'],
             ['Eve', 28, 'Miami']]
df_list = pd.DataFrame(data_list, columns= ['Name', 'Age', 'City'])
print("\nPandas DataFrame from list of lists:")
display(df_list)

In [ ]:
# Accessing Data in DataFrames ---
display(df)
# **Accessing a Specific Column**
# You can easily select a column by its name, which returns a Pandas Series (a 1D labeled array).
print("\nAges column:")
print(df[  ['Name', 'City']   ])

In [ ]:
# Example: Accessing multiple columns
print("\nName and City columns:")
display(df[  ['Name', 'City']   ])

In [ ]:
df

In [ ]:
# Example: Accessing rows by index (loc and iloc)
display(df)


print("\nFirst row using .iloc (integer-location based indexing):")
display(df.iloc[0:1  , 0:2])

print("\nRows for Alice and Charlie using .loc (label-based indexing):")
# display(df.loc[0:1, 'Name'])





display(df.loc[:, 'Name'])   ### uncomment to check the output - explain why do we get this output?


#### NOTE: in .iloc pass the integers and
###        in loc pass the names given to rows as well as columns

In [ ]:
display(df)

# print('\n\nThe selected element', df.iloc[1  ,   1])

print(df.iloc[1, 2])

In [ ]:
# Example: Filtering rows based on a condition
display(df)

print("\nPeople younger than 35:")
print(df['Age'] < 35)


print(df[      df['Age'] < 35     ])


# Question: give those rows of the dataframe where the age is less than 35.

In [ ]:
# Adding/Modifying Columns ---
display(df)
# Example: Adding a new column
df['Occupation'] = ['Engineer', 'Artist', 'Doctor']
print("\nDataFrame after adding 'Occupation' column:")
print(df)




df.loc[1, 'Occupation'] = 'Teacher'
print("\nDataFrame after modifying 'Occupation' column:")
print(df)

In [ ]:
# Example: Modifying an existing column
df['Age'] = df['Age'] + 1 # Increment all ages by 1
print("\nDataFrame after incrementing 'Age':")
print(df)

In [ ]:
# Example: Display the first few rows
print("\nFirst 3 rows (head):")
print(df.head(3))

In [ ]:
# Example: Display the last few rows
print("\nLast 1 rows (tail):")
print(df.tail(1))

In [ ]:
# Example: Get general information about the DataFrame
print("\nDataFrame Info:")
df.info()

In [ ]:
# Basic DataFrame Information and Statistics ---
# The `.describe()` method provides a quick statistical summary of numerical columns of DataFrame,
# including count, mean, standard deviation, min, max, and quartiles.
print("\nDataFrame Description (numerical columns):")
print(df.describe())   # 26, 31, 41

# Quiz 2 would be from Notebooks 3 and 4 and it would be conducted on April 22, 2026.

# Midterm would be conducted on April 29, 2026.

### Pandas offers extensive functionalities for data:
- cleaning
- transformation
- merging and
- aggregation.

This makes it the go-to library for preparing data for artificial intelligence and machine learning tasks.

In [ ]:
### Example to test various dataframe functionalities.
import pandas as pd
mydata = {'Employee Name': ['Ashley','Tom','Jack','John','Alicia'],
    'Specialization': ['Python','Data Science','Data preparation','Data Analysis','Machine Learning'],
    'Experience (years)': [3,5,8,2,4]}
myframe = pd.DataFrame(mydata)  # note capital D and F in DataFrame() constructor
myframe

### Selecting Columns and Custom Indices

We can select a few columns from the DataFrame in any arbitrary order using the `columns` option:

In [ ]:
myframe2 = pd.DataFrame(mydata, columns=['Experience (years)', 'Employee Name'])
myframe2

In [ ]:
# Using index option to specify custom indices
myframe3 = pd.DataFrame(mydata, index=['zero','one','two','three','four'])
myframe3

### Creating a DataFrame from a Matrix

An alternative way to create a DataFrame is to pass:
1. A data matrix
2. An array of labels for the indices (`index` option)
3. An array containing the column names (`columns` option)

We can use `np.arange()` to create an array and `reshape()` to convert it to a matrix:

In [ ]:
import numpy as np
np.arange(15).reshape((3, 5))

In [ ]:
myframe4 = pd.DataFrame(np.arange(15).reshape((3,5)),
    index=['row0','row1','row2'],
    columns=['col0','col1','col2','col3','col4']
                        )
myframe4

### Putting Data Together

The data contained in a Series or DataFrame object can be put together in the following ways:

- **Concatenating**: `pandas.concat()` — concatenates objects along an axis
- **Merging**: `pandas.merge()` — connects rows based on one or more keys (join operations)
- **Combining**: `pandas.DataFrame.combine_first()` — connects overlapped data to fill in missing values

### Concatenating Data

Concatenation links together two or more separate data structures and places them next to each other as a single entity.

In [ ]:
myseries1 = pd.Series(np.random.rand(5), index=[0,1,2,3,4])   # .rand() generates numbers between 0 to 1.    use np.random.randint(0,10, size=5) to generate 5 integers
myseries1

In [ ]:
myseries2 = pd.Series(np.random.rand(5), index=[5,6,7,2,3])
myseries2

In [ ]:
# Concatenate myseries1 and myseries2 (axis=0, default)
print(myseries1, '\n', myseries2)
pd.concat([myseries1, myseries2])

In [ ]:
# axis=1 returns a DataFrame
print(myseries1, '\n', myseries2)

pd.concat([myseries1, myseries2], axis=1)

In [ ]:
# Using keys option along axis=1 sets column names
pd.concat([myseries1, myseries2], axis=1, keys=['series1','series2'])

### Concatenating DataFrames

In [18]:
import pandas as pd
myframe1 = pd.DataFrame({'Student Name': ['A','B','C'],
    'Sex': ['M','F','M'], 'Age': [10, 16, 17], 'School': ['Primary','High','High']})
myframe1

  Student Name Sex  Age   School
0            A   M   10  Primary
1            B   F   16     High
2            C   M   17     High

In [17]:
myframe2 = pd.DataFrame({'Student Name': ['D','E','A'],
    'Class': [9,10,5], 'School': ['High','High','Primary']})
myframe2

  Student Name  Class   School
0            D      9     High
1            E     10     High
2            A      5  Primary

In [19]:
# Concatenate the 2 DataFrames
print(myframe1, '\n\n\n', myframe2)
# pd.concat([myframe1, myframe2])

pd.concat([myframe1, myframe2], axis=1)  # try this one by uncommenting this line

  Student Name Sex  Age   School
0            A   M   10  Primary
1            B   F   16     High
2            C   M   17     High


   Student Name  Class   School
0            D      9     High
1            E     10     High
2            A      5  Primary

  Student Name Sex  Age   School Student Name  Class   School
0            A   M   10  Primary            D      9     High
1            B   F   16     High            E     10     High
2            C   M   17     High            A      5  Primary

### Merging Data

The process of **merging** consists of combining data through the connection of rows using one or more **keys** (common columns in the DataFrames to be merged). The `merge()` function performs this operation.

In [20]:
print(myframe1, '\n\n\n', myframe2)

print(pd.merge(myframe1, myframe2))       # common columns: Student Name and School, Default merge = inner join → only matching rows are kept

# pd.merge(myframe1, myframe2, on='Student Name')

  Student Name Sex  Age   School
0            A   M   10  Primary
1            B   F   16     High
2            C   M   17     High
  Student Name  Class   School
0            D      9     High
1            E     10     High
2            A      5  Primary
  Student Name Sex  Age   School  Class
0            A   M   10  Primary      5

In [5]:
# Merge on a specific column using the 'on' option
print(myframe1, '\n\n\n', myframe2)

pd.merge(myframe1, myframe2, on='School')              # Every row from myframe1 is matched with every row in myframe2 that shares the same School

  Student Name_x Sex  Age   School Student Name_y  Class
0              A   M   10  Primary              A      5
1              B   F   16     High              D      9
2              B   F   16     High              E     10
3              C   M   17     High              D      9
4              C   M   17     High              E     10

In [8]:
#pd.merge(myframe1, myframe2, on='Age')   #   # try this one by uncommenting this line

  Student Name Sex  Age School_x  Class School_y
0            A   M   10  Primary      5  Primary

In [15]:
# Dataframes can be merged on the basis of indices  --- for that we use 'join' method.
print(f'My Frame 1: \n\n {myframe1}')

myframe2.columns = ['Student Name2', 'Class', 'School2']
myframe2.index = [0, 1, 3]

print(f'My Frame 2: \n\n {myframe2}')


print(f'My Frame 1 (left) joined with My Frame 2: \n\n {myframe1.join(myframe2)}')                             # Default: left join

# print(f'My Frame 1 (right) joined with My Frame 2: \n\n {myframe1.join(myframe2, how = 'right')}')           # Right join

My Frame 1:

   Student Name Sex  Age   School
0            A   M   10  Primary
1            B   F   16     High
2            C   M   17     High
My Frame 2:

   Student Name2  Class  School2
0             D      9     High
1             E     10     High
3             A      5  Primary
My Frame 1 (left) joined with My Frame 2:

   Student Name Sex  Age   School Student Name2  Class School2
0            A   M   10  Primary             D    9.0    High
1            B   F   16     High             E   10.0    High
2            C   M   17     High           NaN    NaN     NaN

### Combining Data

The `combine_first()` function is used when we have **two datasets with overlapping indices** and want to keep values from one dataset for overlapping indices, and keep values from the other dataset for non-overlapping indices.

This cannot be obtained with merging or concatenation.

In [10]:
myseries1 = pd.Series([50, 40, 30, 20, 10], index=[1,2,3,4,5])
myseries1

1    50
2    40
3    30
4    20
5    10
dtype: int64

In [11]:
myseries2 = pd.Series([100, 200, 300, 400], index=[3,4,5,6])
myseries2

3    100
4    200
5    300
6    400
dtype: int64

In [12]:
# Keep values from myseries1 for overlapping indices
print(myseries1, '\n\n\n', myseries2, '\n\n\n',)

myseries1.combine_first(myseries2)

1    50
2    40
3    30
4    20
5    10
dtype: int64


 3    100
4    200
5    300
6    400
dtype: int64

1     50
2     40
3     30
4     20
5     10
6    400
dtype: int64

In [13]:
# Keep values from myseries2 for overlapping indices
print(myseries1, '\n\n\n', myseries2, '\n\n\n',)

myseries2.combine_first(myseries1)

1    50
2    40
3    30
4    20
5    10
dtype: int64


 3    100
4    200
5    300
6    400
dtype: int64

1     50
2     40
3    100
4    200
5    300
6    400
dtype: int64

### Data Transformation

The process of **data transformation** involves:
- Removal or replacement of duplicate or invalid values
- Handling outliers
- Handling missing values

### Removing Unwanted Data and Duplicates

- Use `del` command to remove an unwanted **column**
- Use `drop()` function to remove an unwanted **row**

In [ ]:
myframe5 = pd.DataFrame({'Student Name': ['A','B','C'],
    'Sex': ['M','F','M'], 'Age': [10, 16, 17], 'School': ['Primary','High','High']})
del myframe5['School']
myframe5

In [ ]:
# Remove the row indexed 1
myframe5.drop(1)

### Removing Duplicate Rows

Duplicate rows do not convey extra information, consume extra memory, and add to the cost of computations. Use `duplicated()` to detect them and `drop_duplicates()` to remove them.

In [ ]:
item_frame = pd.DataFrame({'Items': ['Ball','Bat','Hockey','Football','Ball'],
    'Color': ['White','Gray','White','Red','White'],
    'Price': [100,500,700,200,100]})
item_frame

In [ ]:
# Detect duplicate rows
item_frame.duplicated()

In [ ]:
# Display only the duplicate entries
item_frame[item_frame.duplicated()]

In [ ]:
# Remove the duplicate entries
item_frame.drop_duplicates()

### Handling Outliers

**Outliers** are values outside the expected range of a feature. Common causes include:
- Human errors during data entry
- Measurement (instrument) errors
- Experimental errors during data extraction or manipulation
- Intentional errors to test accuracy of outlier detection methods

A good approach to detect numeric outliers is to use **InterQuartile Range (IQR)** — the difference between the third (Q3) and first (Q1) quartiles.

Using a typical interquartile multiplier $k = 1.5, 2$ or a bigger value.
- **Lower limit** = $Q1 − (\text{IQR} × 1.5)$
- **Upper limit** = $Q3 + (\text{IQR} × 1.5)$

In [ ]:
student_frame = pd.DataFrame({'Student Name': ['A','B','C','D','E','F','G'],
    'Sex': ['M','F','M','F','F','M','M'],
    'Age': [10, 14, 60, 15, 16, 15, 11],
    'School': ['Primary','High','High','High','High','High','Primary']
    })
student_frame

In [ ]:
# Describe important statistics
student_frame.describe()

In [ ]:
# Calculate lower and upper limits using IQR
Q1 = student_frame['Age'].quantile(0.25)  # 25% (quartile 1)
Q3 = student_frame['Age'].quantile(0.75)  # 75% (quartile 3)
IQR = Q3 - Q1  # InterQuartile Range (IQR)
IQR_mult = IQR * 1.5
lower = Q1 - IQR_mult
upper = Q3 + IQR_mult
print("The lower limit is = ", lower)
print("The upper limit is = ", upper)

In [ ]:
# Filter the DataFrame to remove outliers
student_frame = student_frame[student_frame['Age'] > int(lower)]
student_frame = student_frame[student_frame['Age'] < int(upper)]
student_frame

### Handling Missing or Invalid Data

Missing values in a dataset can be:
- **Ignored** — often not a good solution
- **Filled-in** (Data Imputation) — e.g., mean or median imputation
- **Removed or Dropped** — using `dropna()`

We use `isnull()` to identify missing values:

In [ ]:
myseries4 = pd.Series([10, 20, 30, None, 40, 50, np.nan], index=[0,1,2,3,4,5,6])
print(myseries4.isnull())
myseries4

In [ ]:
# Get indices where values are missing
myseries4[myseries4.isnull()]

In [ ]:
myseries4_dropped = myseries4.dropna()      # if you want to reset the index, use           myseries4_dropped = myseries4.dropna().reset_index()
myseries4_dropped

In [ ]:
# Data Imputation: fill missing values with mean
myseries4_filled = myseries4.fillna(myseries4.mean())
myseries4_filled

### Data Mapping

The Pandas library provides useful **data mapping** functions. Mapping is the creation of a list of matches between two values using dictionary objects.

The following functions accept a dictionary object to perform mapping:
- `replace()` — replaces values
- `map()` — creates a new column
- `rename()` — replaces the index values

In [ ]:
data = {'color': ['blue','green','yellow','red','white'],
    'object': ['ball','pen','pencil','paper','mug'],
    'price': [1.2,1.0,0.6,0.9,1.7]}
myframe = pd.DataFrame(data)
myframe

In [ ]:
# Create a dictionary for mapping and use replace()
mymap = {'blue': 'dark blue', 'green': 'light green'}
myframe.replace(mymap)

In [ ]:
# Use replace() to replace NaN values
myseries = pd.Series([1, 2, np.nan, 4, 5, np.nan])
print(myseries, '\n\n\n')
myseries.replace(np.nan, 0)

In [ ]:
# Use map() to add a new column to the DataFrame
mymap2 = {'ball':'round', 'pencil':'long', 'pen':'long', 'mug':'cylindrical', 'paper':'rectangular'}
myframe['shape'] = myframe['object'].map(mymap2)
myframe

In [ ]:
# Use rename() to rename indices
reindex = {0: 'first', 1: 'second', 2: 'third', 3: 'fourth', 4: 'fifth'}
myframe = myframe.rename(reindex)
myframe

### Discretization and Binning

**Discretization** transforms continuous data into **discrete categories** (bins) to facilitate analysis. For example, dividing a range of values into intervals.

- `pd.cut()` — divides data into **equal-width** bins
- `pd.qcut()` — divides data into **quantile-based** bins (equal number of occurrences per bin)

In [ ]:
readings = [34, 39, 82, 75, 16, 17, 15, 74, 37, 68, 22, 92, 99, 54, 39, 96, 17, 36, 91, 86]

bins = [0, 25, 50, 75, 100]
mycategory = pd.cut(readings, bins)
mycategory
#type(mycategory)   # check the type of mycategory

In [ ]:
readings.sort()
print(readings)

In [ ]:
# Count the number of elements in each bin
pd.value_counts(mycategory)

In [ ]:
# Give meaningful names to the bins
bin_names = ['Poor', 'Below Average', 'Average', 'Good']
pd.cut(readings, bins, labels=bin_names)

In [ ]:
# qcut(): quantile-based binning (equal number of elements per bin) qcut uses the formula cut = (n-1)*p ---> n=20, p=0.25, 0.5, 0.75, 1
cut_values = pd.qcut(readings, 4)

print(cut_values)

In [ ]:
# Check the number of elements in each qcut bin
pd.value_counts(pd.qcut(readings, 4))

### Aggregating Data

**Aggregation** is the process of grouping data together using statistical functions such as mean, median, count, or sum to combine several rows. The combined data is:
- Easier to analyze
- Protects individual privacy
- Can be matched with other data sources

In [ ]:
data = {'color': ['blue','white','red','red','white'],
    'object': ['ball','pen','pencil','paper','mug'],
    'price': [1.2,1.0,0.6,0.9,1.7]}
myframe = pd.DataFrame(data)
myframe

In [ ]:
# Group data based on the column 'color'
mygroup = myframe['price'].groupby(myframe['color'])
print(mygroup.groups)

In [ ]:
mygroup.mean()

In [ ]:
mygroup.sum()

### Hierarchical Grouping

Data aggregation can be performed using **more than 1 column** — this is called **hierarchical grouping**.

In [ ]:
# Group by both color and object
mygroup2 = myframe['price'].groupby([myframe['color'], myframe['object']])
mygroup2.groups

In [ ]:
# Add an extra entry to the DataFrame
myframe2 = myframe
myframe2.loc[5] = ['red','pencil',0.8]
myframe2

In [ ]:
# Group myframe2 by color and object
mygroup2 = myframe2['price'].groupby([myframe2['color'], myframe2['object']])
mygroup2.groups

In [ ]:
mygroup2.mean()

In [ ]:
mygroup2.sum()

### Selection of Data

Sometimes we need to work with a **subset** of a dataset. Let us work on the DataFrame `myframe4` created earlier.

We can inspect the columns, index, and values of a DataFrame:

In [ ]:
# Recreate myframe4 for this section
myframe4 = pd.DataFrame(np.arange(15).reshape((3,5)),
    index=['row0','row1','row2'],
    columns=['col0','col1','col2','col3','col4'])

myframe4.columns

In [ ]:
myframe4.index

In [ ]:
myframe4.values

In [ ]:
# Select a single column
myframe4['col2']

In [ ]:
# Alternatively, use column name as an attribute
myframe4.col2

In [ ]:
# Extract rows with index 1 and 2 (3 excluded)
myframe4[1:3]

In [ ]:
# Access rows by index name using loc
myframe4.loc['row1']

### Naming Rows/Columns, Adding Columns, and Updating Values

In [ ]:
# Give meaningful names to rows and columns
myframe4.index.name = 'Rows'
myframe4.columns.name = 'Columns'
myframe4

In [ ]:
# Add a new column with random values
myframe4['col5'] = np.random.randint(100, size=3)
myframe4

In [ ]:
# Change a single value
myframe4[1, 'col1'] = 1000
myframe4

In [ ]:
# Check membership with isin()
myframe4.isin([1, 4, 99])

In [ ]:
# Use Boolean result as indices (non-matching positions become NaN)
myframe4[myframe4.isin([1, 4, 99])]

In [ ]:
# Delete a column using del
del myframe4['col5']
myframe4

### Conditional Row Selection and Transpose

In [ ]:
# Display myframe3 created earlier
myframe3 = pd.DataFrame(mydata, index=['zero','one','two','three','four'])
myframe3

In [ ]:
# Select employees with more than 4 years of experience
myframe3[myframe3['Experience (years)'] > 4]

In [ ]:
# Transpose a DataFrame
myframe3.T

### Exercise Questions

**Question 1:** Let us write the following commands:
```python
myseries2 = pd.Series([1, -3, 5, 20], index=['a','b','c','d'])
myseries2[2:3]
```
What will be the output?
- A. `c 5`
- B. `b -3 / c 5`
- C. `c 5 / d 20`
- D. `5 c`

**Question 2:** What does `mycolors.unique()` return for the `mycolors` Series defined above?

**Question 3:** We link together two or more separate data structures using?
- A. `pandas.DataFrame.combine_first()`
- B. `pandas.merge()`
- C. `pandas.concat()`
- D. All of the above

**Question 4:** We combine data through the connection of rows using one or more keys by typing?
- A. `pandas.DataFrame.combine_first()`
- B. `pandas.merge()`
- C. `pandas.concat()`
- D. All of the above

**Question 5:** We combine data keeping values from one dataset if an overlapping index comes during combining. For this purpose we use?
- A. `pandas.DataFrame.combine_first()`
- B. `pandas.merge()`
- C. `pandas.concat()`
- D. All of the above


**Question 6:** We combine data by stacking DataFrames vertically (row-wise) without using keys by typing?

- A. `pandas.DataFrame.combine_first()`
- B. `pandas.merge()`
- C. `pandas.concat()`
- D. `pandas.join()`

**Question 7:** We combine data based on index alignment (default join on index) using?

- A. `pandas.DataFrame.join()`
- B. `pandas.merge()`
- C. `pandas.concat()`
- D. `pandas.DataFrame.combine_first()`


Q8. Create a Pandas DataFrame from dictionary and display summary statistics.

Q9. Filter rows in DataFrame where a column value > threshold.

Q10. Add a new column in DataFrame based on condition using apply().

Q11. Group a DataFrame by a column and compute mean of another column.

Q12. Sort DataFrame by multiple columns.

Q13. Merge two DataFrames using a common column.

Q14. Handle missing values in DataFrame using fillna() and dropna().

Q15. Count frequency of values in a column using value_counts().

Q16. Create a dictionary from DataFrame using zip().

Q17. Iterate through DataFrame rows using iterrows() and print values.

Q18. Use enumerate() to add index column manually in DataFrame.

Q19. Apply a custom function using map() to modify a column.

Q20. Use filter() to extract rows where values satisfy condition.

In [ ]:
# Q8

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
print("Q8:\n", df.describe())

# Q9
print("Q9:\n", df[df['A']>1])

# Q10
df['C'] = df['A'].apply(lambda x: x*2 if x>1 else x)
print("Q10:\n", df)

# Q11
df2 = pd.DataFrame({'grp':['A','A','B'],'val':[10,20,30]})
print("Q11:\n", df2.groupby('grp')['val'].mean())

# Q12
print("Q12:\n", df.sort_values(['A','B'], ascending=False))

# Q13
df3 = pd.DataFrame({'A':[1,2],'C':[7,8]})
print("Q13:\n", pd.merge(df, df3, on='A'))

# Q14
df4 = pd.DataFrame({'A':[1,None,3]})
print("Q14:\n", df4.fillna(0), "\n\n", df4.dropna())

# Q15
print("Q15:\n", df2['grp'].value_counts())

# Q16
print("Q16:", dict(zip(df['A'], df['B'])))

# Q17
print("Q17:")
for i,row in df.iterrows():
    print(i, row['A'], row['B'])

# Q18
df['index'] = [i for i,_ in enumerate(df['A'])]
print("Q18:\n", df)

# Q19
df['A'] = list(map(lambda x: x+1, df['A']))
print("Q19:\n", df)

# Q20
filtered = list(filter(lambda x: x>2, df['A']))
print("Q20:", filtered)